name: meeple_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.2.1
  input_quantity: ^2.5.1
  shimmer: ^3.0.0
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  

flutter:
  uses-material-design: true

  assets:
    - assets/images/Ellipse 2.png
    - assets/images/logo.png
    - assets/images/onbording1.png
    - assets/images/onbording2.png
    - assets/images/onbording3.png
    - assets/images/wishlist.png
    - assets/images/cart1.png
    - assets/images/cart2.png
    - assets/images/Pay.png
    - assets/images/product_card_1.png
    - assets/images/product_card_2.png
    - assets/images/product_card_3.png
    - assets/images/product_card4.png
    - assets/images/ad_card.png
    - assets/images/error.png
    - assets/images/readme.png
    - assets/images/reco.gif

  fonts:
    - family: Sf Pro
      fonts:
        - asset: assets/fonts/SFPRODISPLAYREGULAR.OTF
        - asset: assets/fonts/SFPRODISPLAYBOLD.OTF
          weight: 700

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon - edid this.png"
  min_sdk_android: 21
  remove_alpha_ios: true
